sudo: required
dist: trusty

# to avoid exporting gcc4.8
language: none

matrix:
  include:
    - compiler: gcc
      env: CXX=g++-5 CC=gcc-5 QT_BASE=56
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - compiler: clang
      env: CXX=clang++-3.7 CC=clang-3.7 QT_BASE=56
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7


#branches:
  #only:
    #- master


before_install:
  - if [ "$QT_BASE" = "54" ]; then sudo add-apt-repository ppa:beineri/opt-qt542-trusty -y; fi
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt561-trusty -y; fi
  - sudo apt-get update -qq

install:
  - if [ "$QT_BASE" = "54" ]; then sudo apt-get install -qq qt54base; source /opt/qt54/bin/qt54-env.sh; fi
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi

script:
  - mkdir build
  - cd build
  - cmake .. && make -j 4

notifications:
  email: false
