sudo: required
dist: trusty

# to avoid exporting gcc4.8
language: none

matrix:
  include:
    - compiler: gcc
      env: CXX=g++-4.8 CC=gcc-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
    - compiler: clang
      env: CXX=clang++-3.5 CC=clang-3.5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
          packages:
            - clang-3.5


#branches:
  #only:
    #- master


before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install build-essential libgl1-mesa-dev qtbase5-dev

script:
  - mkdir build
  - cd build
  - cmake .. && make -j

notifications:
  email: false
