name: MacOS CMake
on:
  workflow_call:
    inputs:
      extra_resolve_options:
        description: "Extra Resolve Options"
        type: string
        required: false
env:
  EXTRA_RESOLVE_OPTIONS: ${{ github.event.inputs.extra_resolve_options }}
jobs:
  macos_cmake:
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        config:
          - arch: ARM64
            os: big_sur
            name: Apple Big Sur (ARM)
          - arch: x64
            os: big_sur
            name: Apple Big Sur (x86)
          - arch: x64
            os: catalina
            name: Apple Catalina (x86)

    runs-on: [self-hosted, macOS, "${{ matrix.config.os }}", "${{ matrix.config.arch }}", cmake, builder]
    name: ${{ matrix.config.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CMake & Clang versions
        run: |
          cmake --version
          clang --version
      - name: CMake Cleanup
        run: cmake -E remove_directory ${{github.workspace}}/build
      - name: CMake Setup
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: CMake Configure
        env:
          GIT_SSH_COMMAND: "${{ 'ssh -i /home/buildbot/.ssh/id_ed25519 -o IdentitiesOnly=yes' }}"
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: cd build && cmake ${{github.workspace}} -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DSTEINWURF_RESOLVE_OPTIONS="--git_protocol=git@ $EXTRA_RESOLVE_OPTIONS"
      - name: CMake Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .
